### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [38]:
# Vector: Option 1
vector = np.random.uniform(0,1,10)

print(f'Vector of size = {vector.size}: {vector}')

Vector of size = 10: [0.05745564 0.48394112 0.45615062 0.53369189 0.03369368 0.33437138
 0.20481896 0.87962569 0.02726796 0.96036004]


In [34]:
# Vector: Option 2
vec = np.random.rand(10)

print(f'Vector of size = {vec.size}: {vec}')

Vector of size = 10: [0.55659203 0.9412026  0.50278147 0.14239225 0.36151398 0.34403457
 0.55868291 0.29482139 0.8585404  0.664475  ]


In [35]:
# create matrix
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])
print(f'Matrix of dimension {matrix.shape}: \n {matrix}')


Matrix of dimension (3, 3): 
 [[11 14 17]
 [20 23 26]
 [29 32 35]]



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [39]:
# 1
vector = np.round((vector + 10), 2)
vector

array([10.06, 10.48, 10.46, 10.53, 10.03, 10.33, 10.2 , 10.88, 10.03,
       10.96])

In [40]:
# 2
matrix = matrix * 2
matrix

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [42]:
# 3
another_vector = vector ** 2
another_vector

array([101.2036, 109.8304, 109.4116, 110.8809, 100.6009, 106.7089,
       104.04  , 118.3744, 100.6009, 120.1216])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [43]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [44]:
# 1
result_matrix = np.dot(B, A)
display(result_matrix)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [46]:
# 2: (2x2) * (2x1) => (2x1)
display(np.dot(result_matrix, C))

array([[0.5202],
       [0.2846]])

In [49]:
# 3: (2x2) * (2x2) => (2x2)
display(np.dot(result_matrix, D))

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [50]:
# 1
display(result_matrix)
display(result_matrix.T)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [51]:
# 2: no changes
display(vector)
display(vector.T)

array([10.06, 10.48, 10.46, 10.53, 10.03, 10.33, 10.2 , 10.88, 10.03,
       10.96])

array([10.06, 10.48, 10.46, 10.53, 10.03, 10.33, 10.2 , 10.88, 10.03,
       10.96])

In [54]:
# 3: vector == row vector, column_vector == column vector
column_vector = np.expand_dims(vector, axis=1)
display(column_vector)
display(column_vector.shape)

array([[10.06],
       [10.48],
       [10.46],
       [10.53],
       [10.03],
       [10.33],
       [10.2 ],
       [10.88],
       [10.03],
       [10.96]])

(10, 1)

In [55]:
# 4
display(column_vector.T)
display((column_vector.T).shape)

array([[10.06, 10.48, 10.46, 10.53, 10.03, 10.33, 10.2 , 10.88, 10.03,
        10.96]])

(1, 10)